version: "3"

services:
  node:
    image: node:latest
    container_name: node
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: /bin/sh -c "cd /app && npm install && npm run dev"
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    depends_on:
      - node
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
