version: "3"

services:
  node:
    # image: node:latest
    build: .
    container_name: node
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    # command: /bin/sh -c "cd /app && npm install && npm start"
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./docker/postgres:/var/lib/postgresql/data
    depends_on:
      - node

volumes:
  postgres:
